### ISSUE TITLE
GameStop ATC notification Issue

### ISSUE THREAD

**Issue by xmpierce1** [Prince25/StockAlertBot#104]
On certain pages of GameStop, the product page will show Add to Cart for a split second then NOT AVAILABLE. It is not available but trips the BOT to IN STOCK. Can a delay be placed in for GameStop for the BOT to wait before it checks. The link is below with a video demonstrating the sympton 

https://www.gamestop.com/video-games/playstation-5/consoles/products/playstation-5-digital-edition-with-ps-plus-system-bundle-with-20-gamestop-gift-card/B225171U.html

https://user-images.githubusercontent.com/74942520/118863886-6a777a00-b8ad-11eb-8f6c-0ba271ae6fca.mp4

**Comment by Prince25** [comment]
Great idea, good investigation and nice proof but unfortunately, http requests don't work like that. They just get the page without any JavaScript code executing, which is what's happening in this situation. Moreover, inventory status is not fetched from the page for Gamestop, but a database. So if it's tripping for Gamestop, it's because of something going on with their database.

**Comment by Prince25** [comment]
Closed due to inactivity.
