### ISSUE TITLE
Error on Amazon Page

### ISSUE THREAD

**Issue by git-tyl** [Prince25/StockAlertBot#116]
https://www.amazon.com/dp/B097S5SQ3Z

Error occured for AMAZON while checking the item,
gives an error

Writing HTML to logs/amazonErrorPage.html.
		      This is usually not a problem but if this error appears frequently, please report the error with the log and html files to GitHub.

**Comment by Prince25** [comment]
Could you post `amazonErrorPage.html` from the logs folder? Also, refer to the issue #112

**Comment by git-tyl** [comment]
amazon.log
'Unable to get information'
ITEM_INFO: {
    "url": "https://www.amazon.com/dp/B097S5SQ3Z",
    "notificationSent": false,
    "shouldSendNotification": true,
    "info": {},
    "title": "EVGA GeForce RTX 3080 XC3 Ultra Gaming, 10G-P5-3885-KL, 10GB GDDR6X, iCX3 Cooling, ARGB LED, Metal Backplate, LHR",
    "image": "",
    "inventory": false
}

**Comment by git-tyl** [comment]
[amazonErrorPage.html.zip](https://github.com/Prince25/StockAlertBot/files/7086867/amazonErrorPage.html.zip)

**Comment by Prince25** [comment]
@git-tyl Sorry. I totally forgot about this. Does this issue still happen? Do you know if it happened more than once?

**Comment by Prince25** [comment]
Nevertheless, I have fixed the issue and I'll release it in the next update. Lmk if you need it right away.

**Comment by vincentdchn** [comment]
Hello, did you fixed this issue ? Because It stills happening on my side. Any idea ?

**Comment by Prince25** [comment]
@vincentdchn Hello. The issue isn't major. I have fixed it but haven't released it. How often does it happen to you?

**Comment by vincentdchn** [comment]
@Prince25 It happens at every check. I tried with links with all the supported store but I keep getting this error. Tried on Mac OS and Ubuntu 20.04

**Comment by Prince25** [comment]
@vincentdchn Unfortunately, that error isn't because of the code. Amazon is blocking your request. Consider using proxies. Check these posts for more information: https://github.com/Prince25/StockAlertBot/issues/112#issuecomment-873488165 and https://github.com/Prince25/StockAlertBot/issues/83#issuecomment-820612705. You can try [Webshare.io](https://www.webshare.io/).
![image](https://user-images.githubusercontent.com/28243638/136678746-9c0d2725-c7cb-4821-88d7-d6809d9bef3e.png)

Nevertheless, I have added error messages for blocked non-proxy requests in the upcoming update.
