### ISSUE TITLE
Currys error

### ISSUE THREAD

**Issue by devidude8** [Prince25/StockAlertBot#54]
Hi I got this error over the night I'm not sure what the problem is
![Currys Error](https://user-images.githubusercontent.com/56320548/111744628-6dd98f80-8883-11eb-8774-b1d0c0dc0166.png)
[Currys.log](https://github.com/PrinceS25/StockAlertBot/files/6169282/Currys.log)

**Comment by marciomvm** [comment]
The same here!!! Lets wait someone help!

**Comment by Prince25** [comment]
So it seems like they put up a temporary page when they receive high traffic. From the log, I got this:
![image](https://user-images.githubusercontent.com/28243638/111847702-9636ad80-88c6-11eb-9230-3c5c314279f3.png)

I doubt this happens at other times but if they're receiving high traffic, it usually means something is dropping. Let me know if it's still happening or if it happens again. For now, I can add a message notifying you of this page if it'll help you guys.

**Comment by waiyujack** [comment]
Hi @Prince25 

I am wondering if you add can something to restart the process automatically if the above error occurs?

**Comment by Prince25** [comment]
@waiyujack I'm currently waiting on @devidude8 and @marciomvm to see what they prefer when this happens but you can do something like [this](https://stackoverflow.com/questions/42820624/auto-restart-batch-file-upon-exit-from-batch) if you use Windows. I'm sure there's a similar solution for other OS.

**Comment by waiyujack** [comment]
> @waiyujack I'm currently waiting on @devidude8 and @marciomvm to see what they prefer when this happens but you can do something like [this](https://stackoverflow.com/questions/42820624/auto-restart-batch-file-upon-exit-from-batch) if you use Windows. I'm sure there's a similar solution for other OS.

Ahh thanks @Prince25 that's really useful!

**Comment by devidude8** [comment]
I'm so sorry for the late reply, I would appreciate if you could add that message notifying us of that page.

**Comment by waiyujack** [comment]
Hi @Prince25 

I have created two bat files. `first.bat`  is to start the bot and `second.bat` is for looping first bat if it ends for any reason. 

However, `npm start` doesn't end when errors occur. It will keep throwing error messages so the solution in the link you provide doesn't quite work. I was wondering if you can provide a quick tweak for me?

`first.bat` :

```
@echo off
npm start
```

`second.bat`:
```
@echo off
:loop
Start first.bat | set /P "="
goto loop
```

**Comment by Prince25** [comment]
Will do. Hang tight!

**Comment by Prince25** [comment]
Try out the new update (cdbe33b). You *should* see a text update if that page is live and if you have `OPEN_URL` turned on, it will also open the page in case it's being restocked. Both of these things have a cooldown of 5 minutes. Please let me know if do or don't see these alerts as I'm not running checking Currys on my end.

**Comment by waiyujack** [comment]
Thanks a lot @Prince25!

Apart from the temporary page, I think you can get the same error when you set a small value for the retry interval (say 1 sec).

Once you get this error, it will keep throwing the error ( I guess it won't go look up the page properly)

Just wondering you could add a fix to restart it when it gets the error.

**Comment by Prince25** [comment]
@waiyujack by same error, you mean the 503 status code or "getting more traffic than usual"? If you set a low interval without using proxies, it will most likely result in the site banning you in which case, I cannot do anything about.

As for the restart, I thought you said the program doesn't end when it gets the error so restart is not necessary.

**Comment by waiyujack** [comment]
Hi @Prince25 thanks for getting back. I believe the errors come from the site banning me since I am not using proxies.

Basically, if I set an interval say 1sec your tool will work fine for 20 secs and then it will get errors (or banned) forever.

However, if I close the existing cmd prompt and open a new one, the new one would work fine again (for 20 secs).

So I believe currys are banning the session but not my ip and that's why I ask whether we can restart it?

**Comment by waiyujack** [comment]
> Hi @Prince25 thanks for getting back. I believe the errors come from the site banning me since I am not using proxies.
> 
> Basically, if I set an interval say 1sec your tool will work fine for 20 secs and then it will get errors (or banned) forever (literally printing out errors every single second)
> 
> However, if I close the existing cmd prompt and open a new one, the new one would work fine again (for 20 secs).
> 
> So I believe currys are banning the session but not my ip and that's why I ask whether we can restart the tool?
> 
> As for your second comment about the program doesn't end, no it doesn't end but it's giving the errors every second. I was wondering if it's still working properly when it gets to that error stage.
> 
> ![PXL_20210325_012437054](https://user-images.githubusercontent.com/46226344/112405245-d1dbd800-8d09-11eb-8c03-3f896cefb0be.jpg)

**Comment by Prince25** [comment]
@waiyujack Honestly 1 second is too low for any website but if you accept the risks, it's all up to you. I see what you mean about the error though. What might be happening is that the program is sending too many requests at once. Currys does not have the delay between items feature as Amazon does. However, I'm in the process of rewriting all the code from scratch so this problem should be resolved in the new update. Meanwhile, a temporary solution for you would be to add `process.exit()` under lines 62 and 105 in `stores/currys.js`. This will exit the program once an error occurs. Again, be cautious though because if you're sending insane amount of requests in a short amount of time, they might just outright ban your IP.

However, what I strongly recommend you to do is the following. Find and use some free proxies. Then make copies of the program folder. In each copy, have 5 or so URLs and set interval to at least 10 seconds (if you don't use proxies). Launch each copy independently and make sure to space out the launches by whatever interval you set. This will make sure the 20+ requests are not being sent in milliseconds.

**Comment by waiyujack** [comment]
Hi @Prince25

Thanks for your explanations of what's happening behind the scene. The UK gpu market is so mad that a second means a lot. I was trying 5s before which gave no errors. However, 5s was just too long and didn't manage to detect a stock (while I got an alert from discord).  Having said that... I don't think I will manage to get one single gpu even 1s is working properly :( 

But yeah thanks for your solution on the `process.exit()` and proxies. I will try those out tonight.

I will also try to adapt some python scripts and see how it compares. Will keep you in the loop :) Whether or not I manage to get a gpu at the end it's just so satisfying and fun to learn a bit programming and use it in a real world case.

**Comment by Prince25** [comment]
@waiyujack glad to hear it. Add me on discord if you need tips or guidance on programming. I know it's hard to get things right now but understand that 1 second interval without proxies is a very bad idea. I'll try to finish the new update as soon as I can but if this program helps you at all, please share and leave a donation. 😄

**Comment by Prince25** [comment]
@devidude8 @marciomvm Let me know if any other issues arise. Closing this for now.
