### ISSUE TITLE
Amazon issue

### ISSUE THREAD

**Issue by gamerover98** [Prince25/StockAlertBot#55]
**Description**

Hello, I've tried this software with a simple item (always available on Amazon) but, the bot throws me the not in the stock message: "4:03:12 PM: "Pilot 289727 Penna a Sfera" not in stock at Amazon. Will keep retrying in background every 10 seconds".

Amazon item URL: https://www.amazon.it/Pilot-289727-Penna-a-Sfera/dp/B00SYCAJ9I
config: https://pastebin.com/iSKiAZD0 (I've removed my personal values)

I've tried to change the IP address with PPPoE and with a VPN but still nothing.

**Comment by Prince25** [comment]
Hi! It seems like your issue is similar to #45 so take a look there. In [one](https://github.com/Prince25/StockAlertBot/issues/45#issuecomment-791835728) of the comments, I highlighted a temporary solution so please give it a try and let me know if the issue persists. If you could find the merchant ID for the Italian Amazon, that'll be helpful as well. :)

**Comment by gamerover98** [comment]
Thank you dude, it works fine!

**Comment by Prince25** [comment]
Good to hear it worked for you. Please consider sharing and donating if the project helps you out.

**Comment by Prince25** [comment]
@gamerover98 Just to let you know, I've added the ability to change Amazon Regions or use particular merchants in 2006dca. So it should now work with non-US regions without any editing.
